name: Build and Release Application

on:
  push:
    tags:
      - v*.*.*

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Install opencv and ffmpeg
        run: brew install ffmpeg opencv
      - name: Download source
        uses: actions/checkout@v2
      - name: Setup node v17
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: Install Dependencies
        run: yarn
      - name: Build app
        run: ./build.sh
      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: STASYS-macos
          path: out/STASYS.dmg

  release_app:
    runs-on: ubuntu-latest
    needs: [build_macos]
    steps:
      - name: Download macos app
        uses: actions/download-artifact@v3
        with:
          name: STASYS-macos
      - name: Release macos app
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            STASYS-macos.dmg